default:
  batchmode: false
  cachedb: "sqlite"
  cacheformat: "qs"
  climategcm: "CNRM-ESM2-1" ## '13GCMs_ensemble', 'CanESM5', 'CNRM-ESM2-1', 'CCSM4'
  climatessp: 370 ## 245, 370, 585
  cloud:
    cachedir: ""
    googleuser: ""
    usecloud: false
  codechecks: true
  delaystart: 0
  inputpaths: null
  messagingNumCharsModule: 21
  paths:
    cachedir: "cache"
    scratchdir: "/tmp/scratch/ON"
  plot: true
  reproduciblealgorithm: 2
  reupload: false
  resolution: 250  ## 250 for AOU; 125 for ROF
  studyarea: "ROF" ## "AOU" or "ROF"
  uselandrcs: true
  usememoise: false
  useprerun: true
  userequire: true

production:
  batchmode: true
  codechecks: false
  delaystart: !expr sample(15L:45L, 1) # 15-45 minute delay to stagger starts
  plot: false

test:
  plot: true

alex:
  inherits: production
  cachedb: "postgresql"
  cloud:
    cachedir: "ON_cloudCache" ## TODO: create and test this
    googleuser: "achubaty@for-cast.ca"
    usecloud: false
  codechecks: true ## TODO: set 'false' once working
  paths:
    scratchdir: !expr if (grepl("forcast(01|02)", Sys.info()[["nodename"]])) "/mnt/scratch/ON" else "/tmp/scratch/ON"
  reupload: !expr if (grepl("forcast02", Sys.info()[["nodename"]])) TRUE else FALSE
  slackchannel: "@alex.chubaty"
  useprerun: false
