default:
  batchmode: false
  cachedb: "sqlite"
  cacheformat: "qs"
  climategcm: "CNRM-ESM2-1" ## '13GCMs_ensemble', 'CanESM5', 'CNRM-ESM2-1', 'CCSM4'
  climatessp: 370 ## 245, 370, 585
  cloud:
    cachedir: ""
    googleuser: ""
    usecloud: false
  codechecks: true
  delaystart: 0
  ecozone: "shield" ## 'plain' or 'shield'
  inputpaths: null
  messagingNumCharsModule: 21
  nreps: 5
  paths:
    cachedir: "cache"
    inputpaths: null
    libpathdeoptim: !expr Require::checkPath(ifelse(nzchar(Sys.getenv("PRJ_PKG_DIR")), Sys.getenv("PRJ_PKG_DIR"), "packages"))
    scratchdir: !expr file.path(dirname(tempdir()), "scratch", "ON")
  plot: false
  reproduciblealgorithm: 2
  reupload: false
  run: 1
  simfileformat: "qs"
  studyarea: "ROF" ## "AOU" or "ROF"
  uselandrcs: false ## hardcoded FALSE if studyArea is "ROF"
  usememoise: false
  useprerun: true
  userequire: true
  useterra: true

production:
  batchmode: true
  codechecks: false
  delaystart: !expr sample(15L:45L, 1) # 15-45 minute delay to stagger starts
  plot: false

test:
  plot: true

alex:
  inherits: production
  cachedb: "postgresql"
  cacheformat: "qs"
  cloud:
    #cachedir: ""
    googleuser: "achubaty@for-cast.ca"
    usecloud: false ## TODO: use cloud cache
  codechecks: false ## TODO: set false after all fixed
  messagingNumCharsModule: 36
  nreps: 5
  paths:
    libpathdeoptim: "~/GitHub/Ontario_AOU_ROF/packages"
    scratchdir: !expr if (grepl("for-cast[.]ca", Sys.info()[["nodename"]])) "/mnt/scratch/WBI_forecasts" else "/tmp/scratch/WBI_forecasts"
  reupload: !expr if (grepl("picea", Sys.info()[["nodename"]])) TRUE else FALSE
  simfileformat: "qs"
  slackchannel: "@alex.chubaty"
  studyArea: "ROF"
  useprerun: false

ian:
  inherits: default
  batchmode: false
  cachedb: "sqlite"
  cacheformat: "qs"
  climategcm: "CNRM-ESM2-1" ## '13GCMs_ensemble', 'CanESM5', 'CNRM-ESM2-1', 'CCSM4'
  climatessp: 370 ## 245, 370, 585
  cloud:
    cachedir: ""
    googleuser: ""
    usecloud: false
  ecozone: "plain" ## 'plain' or 'shield'
  inputpaths: null
  messagingNumCharsModule: 21
  nreps: 10
  paths:
    cachedir: "cache"
    scratchdir: "/tmp/scratch/ieddy/ON"
  plot: false
  reproduciblealgorithm: 2
  reupload: false
  resolution: 125  ## 250 for AOU; 125 for ROF
  run: 1
  simfileformat: "qs"
  studyarea: "ROF" ## "AOU" or "ROF"
  usememoise: false
  useprerun: true
  userequire: true
  useterra: true
