default:
  batchmode: false
  cachedb: "sqlite"
  cloud:
    cachedir: ""
    googleuser: ""
    usecloud: false
  delaystart: 0
  gcm: "CCSM4"
  paths:
    cachedir: "cache"
    scratchdir: "/tmp/scratch/ON"
  plot: true
  rcp: 85
  rep: 1
  resolution: 250  ## 250 for AOU; 125 for ROF
  studyarea: "AOU" ## "AOU" or "ROF"
  upload: true

production:
  batchmode: true
  delaystart: !expr sample(5L:15L, 1) # 5-15 minute delay to stagger starts
  plot: false

test:
  plot: true
  upload: false

alex:
  inherits: production
  cachedb: "postgresql"
  cloud:
    cachedir: "ON_cloudCache" ## TODO: create and test this
    googleuser: "achubaty@for-cast.ca"
    usecloud: false
  paths:
    scratchdir: !expr if (Sys.info()[["nodename"]] == "forcast03") "/tmp/scratch/ON" else "/mnt/scratch/ON"
  slackchannel: "@alex.chubaty"
  upload: false
