default:
  batchmode: false
  cachedb: "sqlite"
  cacheformat: "qs"
  climategcm: "CNRM-ESM2-1" ## '13GCMs_ensemble', 'CanESM5', 'CNRM-ESM2-1', 'CCSM4'
  climatessp: 370 ## 245, 370, 585
  cloud:
    cachedir: ""
    googleuser: ""
    usecloud: false
  codechecks: true
  delaystart: 0
  ecozone: "plain" ## 'plain' or 'shield'
  inputpaths: null
  messagingNumCharsModule: 21
  nreps: 10
  paths:
    cachedir: "cache"
    scratchdir: "/tmp/scratch/ON"
  plot: true
  reproduciblealgorithm: 2
  reupload: false
  resolution: 250  ## 250 for AOU; 125 for ROF
  run: 1
  simfileformat: "qs"
  studyarea: "ROF" ## "AOU" or "ROF"
  uselandrcs: false ## hardcoded FALSE if studyArea is "ROF"
  usememoise: false
  useprerun: true
  userequire: true
  useterra: true

production:
  batchmode: true
  codechecks: false
  delaystart: !expr sample(15L:45L, 1) # 15-45 minute delay to stagger starts
  plot: false

test:
  plot: true

alex:
  inherits: production
  cachedb: "postgresql"
  cacheformat: "qs"
  cloud:
    #cachedir: ""
    googleuser: "achubaty@for-cast.ca"
    usecloud: false ## TODO: use cloud cache
  codechecks: false ## TODO: set false after all fixed
  nreps: 5
  paths:
    scratchdir: !expr if (grepl("for-cast[.]ca", Sys.info()[["nodename"]])) "/mnt/scratch/WBI_forecasts" else "/tmp/scratch/WBI_forecasts"
  reupload: !expr if (grepl("picea", Sys.info()[["nodename"]])) TRUE else FALSE
  simfileformat: "qs"
  slackchannel: "@alex.chubaty"
  studyArea: "ROF"
  useprerun: false

ian:
 inherits: default
 cloud:
  googleuser: "ianmseddy@gmail.com"
 paths:
  scratchdir: "D:/temp"
 useprerun: false
 studyarea: "ROF"
 run: 1
 plot: false
 resolution: 125

