default:
  batchmode: false
  cachedb: "sqlite"
  cloud:
    cachedir: ""
    googleuser: ""
    usecloud: false
  paths:
    cachedir: "cache"
    scratchdir: "/tmp/scratch/ON"
  plot: true
  resolution: 250

production:
  batchmode: true
  plot: true ## TODO: disable

alex:
  inherits: production
  cachedb: "postgresql"
  cloud:
    cachedir: "ON_cloudCache" ## TODO: create and test this
    googleuser: "achubaty@for-cast.ca"
    usecloud: false
  paths:
    scratchdir: !expr if (Sys.info()[["nodename"]] == "forcast03") "/tmp/scratch/ON" else "/mnt/scratch/ON"
  slackchannel: "@alex.chubaty"

